name: flow_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_riverpod: 
  riverpod_annotation:

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: 
  riverpod_lint:

flutter:
  uses-material-design: true
